services:
    - type: web
    name: lar-ditoso
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
            - key: PYTHON_VERSION
        value: 3.10.0
            - key: OAUTHLIB_INSECURE_TRANSPORT
        value: 1